---
# For some reason cloud-init-local, cloud-config, and cloud-final are
# not enabled in the base Kali AMI.  We need cloud-config enabled, and
# we may as well enable the others while we're at it.
#
# According to the link below, it should only be necessary to activate
# cloud-init-main and cloud-final due to the way cloud-init works as
# of version 24.3 of cloud-init:
# https://wiki.archlinux.org/title/Cloud-init#systemd_integration
#
# Fedora 43 currently (January 9, 2026) offers version 25.2 of
# cloud-init.
- name: Ensure necessary cloud-init services are enabled
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  tasks:
    - name: Ensure necessary cloud-init services are enabled
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: true
      loop:
        - cloud-init-main
        - cloud-final
